//! Disk-level blueprint scanning and compilation.
//!
//! Walks a project root looking for `graph_save.json` files, compiles each
//! one with PBGC, and returns the results as [`crate::project::CompiledBlueprint`]s
//! ready to be handed to [`crate::project::generate_project`].

use std::path::{Path, PathBuf};

use crate::compiler::{compile_graph, compile_graph_with_variables};
use crate::project::{generate_project, CompiledBlueprint, GeneratedProject, ProjectSpec};
use graphy::{DataType, GraphDescription, TypeInfo};
use serde::Deserialize;
use std::collections::HashMap;

#[derive(Debug, Deserialize)]
struct BlueprintAssetFile {
    #[serde(alias = "mainGraph")]
    main_graph: GraphDescription,
    #[serde(default)]
    variables: Vec<ClassVariableFile>,
}

#[derive(Debug, Deserialize)]
struct ClassVariableFile {
    name: String,
    data_type: DataType,
    #[serde(default)]
    default_value: Option<String>,
}

/// Compile every blueprint found under `project_root`.
///
/// Recurses through the directory tree looking for folders that contain a
/// `graph_save.json` file.  Each one is compiled with PBGC.  Folders that
/// fail to compile are logged and skipped rather than aborting the whole run.
///
/// Returns `Err` only if the root path cannot be read at all.
pub fn compile_project(project_root: &Path) -> Result<Vec<CompiledBlueprint>, String> {
    let folders = find_blueprint_folders(project_root);
    let mut blueprints = Vec::new();

    for folder in &folders {
        match compile_blueprint_folder(folder) {
            Ok(compiled) => {
                blueprints.push(compiled);
            }
            Err(e) => {
                tracing::warn!(
                    "[PBGC] Skipping blueprint folder {}: {}",
                    folder.display(),
                    e
                );
            }
        }
    }

    Ok(blueprints)
}

/// Compile all blueprints under `project_root` and return generated class files.
///
/// This ensures output contains actor structs and `#[derive(EngineClass)]`
/// wrappers instead of returning only raw PBGC logic.
pub fn compile_project_generated(project_root: &Path) -> Result<GeneratedProject, String> {
    let crate_name = project_root
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("pulsar_project")
        .replace([' ', '-'], "_")
        .to_ascii_lowercase();

    let compiled = compile_project(project_root)?;

    let mut spec = ProjectSpec::new(crate_name).description("Generated by PBGC");
    for bp in compiled {
        spec = spec.add_blueprint(bp);
    }

    Ok(generate_project(&spec))
}

/// Compile a single blueprint folder that contains `graph_save.json`.
fn compile_blueprint_folder(folder: &Path) -> Result<CompiledBlueprint, String> {
    let graph_file = folder.join("graph_save.json");
    let json = std::fs::read_to_string(&graph_file)
        .map_err(|e| format!("Cannot read {}: {}", graph_file.display(), e))?;

    let blueprint_name = folder
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unnamed_blueprint")
        .to_owned();

    if let Ok(asset) = serde_json::from_str::<BlueprintAssetFile>(&json) {
        let variables = compiled_variables(&asset.variables);
        let source = if variables.is_empty() {
            compile_graph(&asset.main_graph).map_err(|e| format!("Compilation error: {e}"))?
        } else {
            let variable_types = variables
                .iter()
                .map(|var| (var.name.clone(), var.rust_type.clone()))
                .collect::<HashMap<_, _>>();

            compile_graph_with_variables(&asset.main_graph, variable_types)
                .map_err(|e| format!("Compilation error: {e}"))?
        };

        return Ok(CompiledBlueprint::new(blueprint_name, source).with_variables(variables));
    }

    let graph: graphy::GraphDescription = serde_json::from_str(&json)
        .map_err(|e| format!("Cannot parse {}: {}", graph_file.display(), e))?;

    let source = compile_graph(&graph).map_err(|e| format!("Compilation error: {e}"))?;
    Ok(CompiledBlueprint::new(blueprint_name, source))
}

fn compiled_variables(variables: &[ClassVariableFile]) -> Vec<crate::project::CompiledVariable> {
    variables
        .iter()
        .map(|var| crate::project::CompiledVariable {
            name: var.name.clone(),
            rust_type: rust_type_for_data_type(&var.data_type),
            default_value: var.default_value.clone(),
        })
        .collect()
}

fn rust_type_for_data_type(data_type: &DataType) -> String {
    match data_type {
        DataType::Data(ti) => ti.type_string.clone(),
        DataType::Exec => "()".to_string(),
    }
}

/// Recursively find every directory that contains a `graph_save.json`.
fn find_blueprint_folders(root: &Path) -> Vec<PathBuf> {
    let mut result = Vec::new();
    walk_for_blueprints(root, &mut result);
    result
}

fn walk_for_blueprints(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.join("graph_save.json").exists() {
                out.push(path.clone());
            }
            walk_for_blueprints(&path, out);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use graphy::{
        DataType, GraphDescription, NodeInstance, Pin, PinInstance, PinType, Position, TypeInfo,
    };

    fn unique_temp_dir(prefix: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("{}_{}", prefix, nanos))
    }

    #[test]
    fn compile_project_reads_blueprint_asset_variables() {
        let root = unique_temp_dir("pbgc_disk_asset_vars");
        let class_dir = root.join("PlayerClass");
        std::fs::create_dir_all(&class_dir).unwrap();

        let mut graph = GraphDescription::new("player_graph");
        let mut begin = NodeInstance::new("begin", "begin_play", Position { x: 0.0, y: 0.0 });
        begin.outputs.push(PinInstance::new(
            "begin_exec",
            Pin::new("begin_exec", "Body", DataType::Exec, PinType::Output),
        ));
        graph.add_node(begin);
        let graph_value = serde_json::to_value(&graph).unwrap();
        let asset_value = serde_json::json!({
                "format_version": 1,
                "mainGraph": graph_value,
                "variables": [
                        {
                                "id": "var_1",
                                "name": "health",
                                "data_type": graphy::DataType::typed("f64"),
                                "default_value": "100.0",
                                "description": ""
                        }
                ]
        });

        std::fs::write(
            class_dir.join("graph_save.json"),
            serde_json::to_string_pretty(&asset_value).unwrap(),
        )
        .unwrap();

        let compiled_single = compile_blueprint_folder(&class_dir).unwrap();
        assert_eq!(compiled_single.variables.len(), 1);
        assert_eq!(compiled_single.variables[0].name, "health");

        let compiled = compile_project(&root).unwrap();
        assert_eq!(compiled.len(), 1);
        assert_eq!(compiled[0].name, "PlayerClass");
        assert_eq!(compiled[0].variables.len(), 1);
        assert_eq!(compiled[0].variables[0].name, "health");

        let generated = compile_project_generated(&root).unwrap();
        assert!(generated
            .files
            .contains_key("src/classes/player_class/mod.rs"));
        assert!(generated
            .files
            .contains_key("src/classes/player_class/events/mod.rs"));
        assert!(generated
            .files
            .contains_key("src/classes/player_class/events/events.rs"));
        assert!(generated
            .files
            .contains_key("src/classes/player_class/vars/mod.rs"));

        let _ = std::fs::remove_dir_all(&root);
    }
}
